version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:current
    steps:
      - checkout
      - run:
          name: Install dependences
          command: |
            npm install --save
      - run:
          name: Run build
          command: |
            npm run build
      - run:
          name: Run tests
          command: |
            npm run test
workflows:
  build_tests:
    jobs:
      - run_tests